name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # This is the critical permission addition
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration production --base-href /advocate-website/

      - name: Create 404 page for SPA routing
        run: cp dist/advocate-website/browser/index.html dist/advocate-website/browser/404.html

      - name: Add .nojekyll file
        run: touch dist/advocate-website/browser/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: dist/advocate-website/browser
          branch: gh-pages
          clean: true
